### ISSUE TITLE
Upgrade to latest generator build

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-accordion#11]
# General Support Request

The scope of this issue is to address needed upgrades for Auro Accordion.

Recommended to create a new repo with the installer and port over the core functional component code.

NOTE: There was a test with migrating the demo page to markdown and the `<auro-accordion-group>` was not operating as expected. This may need to be investigated prior to doing the work. 

### Prior to next major release 

It is **important that we communicate prior to the next major release** that we will be changing the npm namespace.  

```shell
$ npm deprecate @alaskaairux/auro-accordion@1.x "v1.x is no longer supported. Please see @aurodesignsystem/auro-accordion for further updates"
```

**Comment by blackfalcon** [comment]
On hold until WC-Generator 3.0 is released

**Comment by Patrick-Daly-AA** [comment]
should be completed in coordination with #70
