### ISSUE TITLE
Theme Support

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-accordion#115]
### Is your feature request related to a problem? Please describe.

Support new Tier 3 token structure and theme support

### Describe the solution you'd like

Component should support the new beta release pattern for our components to support theme enabled tokens

### Describe alternatives you've considered

None

**Comment by jordanjones243** [comment]
This is blocked until auro-button's color theming bugs are fixed:
- https://github.com/AlaskaAirlines/auro-button/issues/253
