### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-accordion#27]
## NEXT MAJOR release 

The following items are to be included with the next MAJOR release of the Auro WC-Generator, all PRs are to be from the feature branch to `v2.0-rc` branch.

### Review for release 
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/30
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/29
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/28

### Consider closing in favor of new work (#28)
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/24
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/23
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/16

### Final upgrade prior to release 
- [ ] https://github.com/AlaskaAirlines/auro-accordion/issues/11

**Comment by braven112** [comment]
closing this rc in favor of individual issues and the milestone
