### ISSUE TITLE
auro-accordion: expanded not working

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-accordion#3]
# Describe the bug

Using the `expanded` feature on the component does not appear to be pre-expanding the UI as expected. 

## To Reproduce

Using `<auro-accordion expanded>` doesn't work. 

## Expected behavior

The component should be expanded on load.

## Desktop (please complete the following information):

 - Browser [chrome, safari]

**Comment by geoffrich** [comment]
I'm going to try to fix this. I think it's related to how the height transition is performed.
