### ISSUE TITLE
Custom variant found in the wild

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-accordion#41]
# General Support Request

New work done with the Contract Tracing project shows a custom variant on the accordion element as shown in the Gif below. 

[demo link as of 12/1/21](https://reservations.qa.alaskaair.com/ssrs/contactinfo?confirmationCode=INZKKT&lastName=Tester)

![Dec-01-2021 13-17-36](https://user-images.githubusercontent.com/181089/144315602-140d10d0-9114-4ef1-b60a-1e2b980c4365.gif)

## Support request

There are few things we can do to keep people from doing things like this. The question is, how do we want to manage this? The custom variant is not part of the element nor has it been presented as an option to consider. So this will also not be a part of any blueprint created now or in the future. 

## Possible Solution

What is the proper restraint and line we need to hold all designers to so that custom variants like this don't happen? Or... do we simply not care that this happens? 

If we don't care, who is ultimately on the hook for supporting that idea? When this team leaves and the code is still there, can they hold us accountable if something goes wrong? If we release an update that breaks their customization, do we need to respond? 

I feel that we need to have an official position on this as to inform others going forward and protect ourselves as well.

**Comment by leeejune** [comment]
This is one example of projects that were on a deadline and needed something ASAP. I agree that we need to have a more solid plan around these cases and let everybody know!

**Comment by leeejune** [comment]
Will be addressed in issue #69.
