### ISSUE TITLE
auro-accordion; develop [feature]

### ISSUE THREAD

**Issue by Luno89** [AlaskaAirlines/auro-accordion#55]
# User story

As a user on Alaska Air, I want to be able to clearly understand the scope of the accordion, so I can interact with enclosing elements with the context of the title. 

Allows product teams to comply with the design work that includes the auro-accordion without a line between the title and the content.

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- [ ] pass in a parameter that removes the line between the content and the title

## Definition of “Done” (exit criteria)

The line under the title in the accordion should be optional (able to be turned off from displaying)

#### Auro component features

- [ ] README doc completed with all relative information
- [ ] API documentation created
- [ ] Bundled version tested and documented
- [ ] Examples and use case info created
- [ ] Pages added to the Auro Doc Site

## Audit

https://github.com/AlaskaAirlines/auro/issues/[issue number]

**Comment by braven112** [comment]
Pending discussion with designers

**Comment by blackfalcon** [comment]
New design work has been addressed with accordion since this issue has been created. Please reference https://www.figma.com/file/VpUz89Ov6ImBpY5YvzYbZW/Auro-toolkit?node-id=2441%3A15307
