### ISSUE TITLE
auro-accordion: Allow deep-linking to an accordian item

### ISSUE THREAD

**Issue by jeremeevans** [AlaskaAirlines/auro-accordion#56]
## Is your feature request related to a problem? Please describe.
The business would like to create deep links to specific Auro accordion items. For example, a link to the "Pets in the cabin" accordion item on this page: https://www.alaskaair.com/content/travel-info/policies/pets-traveling-with-pets 

## Describe the solution you'd like
I would like anchors specified for every accordion item so that we can create deep links. For example, something like this:
https://www.alaskaair.com/content/travel-info/policies/pets-traveling-with-pets#pets-in-the-cabin

would link to that specific accordion item and have it expanded.

## Describe alternatives you've considered
Force everyone to rewrite everything using headings and anchors and abandon the accordion.

## Additional context
Self-exclamatory...

**Comment by braven112** [comment]
Thanks for the feature request, this would definitely be a good idea.  We'll add this to our backlog.

**Comment by blackfalcon** [comment]
@jeremeevans regarding this feature request, is this something you need now, later or ...

**Comment by jeremeevans** [comment]
> @jeremeevans regarding this feature request, is this something you need now, later or ...

James Tsai and Elena Zubowicz need it sooner than later. I'm not sure what the process of updating the Auro components in .com is, but that will have to happen, too. They want to link to specific items for disclosures during the check-in process. I believe they want to have a final design for updating that by the end of September. Should we start an email thread with them?

**Comment by blackfalcon** [comment]
@jeremeevans for this new feature request, it would be very helpful if @leeejune was involved in the design process so that we can clearly see what the new feature is. From there we can prioritize the work if not get support from your team to add the feature. 

Once the feature is clearly defined from a UX perspective, I would suggest that we create a new issue with the specific specification for the feature with a link to the approved Figma docs and that's what we would plan to deliver.

**Comment by blackfalcon** [comment]
This issue is pretty aged and there is no resolution recommendation I am aware of. @jeremeevans is this a feature you are still interested in using? @leeejune has there been any discussion with designers?

**Comment by blackfalcon** [comment]
As of today, consulting with design staff, this issue is not on any agenda to be addressed. Will review in 30 days and if there is no new information this issue will be closed.

**Comment by leeejune** [comment]
There has been discussion among the UI team, but no clear conclusion. The example "pets" page has also been updated, so there are no live examples.

**Comment by blackfalcon** [comment]
There has been no feedback from the author of this issue and design has yet to come to a conclusion. If at such time there is a clear direction from UX, we can discuss this as a feature.
