### ISSUE TITLE
Redesigning accordion experience (workshop)

### ISSUE THREAD

**Issue by leeejune** [AlaskaAirlines/auro-accordion#69]
## Is your feature request related to a problem? Please describe.
User studies have shown that users do not recognize the accordion on a content heavy space.

## Describe the solution you'd like
Design an accordion with more affordance and discover new ways to indicate that the accordion is interactive. We should also have guidelines for the header text (change to actionable text).

## Describe alternatives you've considered
Use current accordion.

## Additional context
Usertesting video that highlights the issues with accordion we designed for the Air Tahiti Nui page:
https://app.usertesting.com/h/viRinNuL5WCRDVDLV9D-?shared_via=link

Existing Auro accordion on a live page: https://www.alaskaair.com/content/mileage-plan/use-miles/award-charts

**Comment by leeejune** [comment]
Working on this with Jeannie Kao, product designer.

**Comment by leeejune** [comment]
[Figma file](https://www.figma.com/file/OtOeXysxg6ExR7zeqVgeLb/Accordion-Workshop?node-id=1%3A7&t=qu2mUIjhp2YpEYLS-1)

## Session 1 (3/2): Understanding Context

- Where is accordion being used?
- What are existing research studies can we refer to?

**Comment by bbrdnx** [comment]
Manage team has begun working with a new version of the accordion component from component hangar. Here are screenshots of how we plan to use it. We will update our component with the Auro official version when available. 

![accordion component 2](https://user-images.githubusercontent.com/47824996/226065011-310fdc7a-294f-4e5e-907c-5916b2e62a86.png)
![cart design mobile-1](https://user-images.githubusercontent.com/47824996/226065013-71805b99-7fcc-45ce-a8d9-e5dee69780fd.png)
![cart design mobile](https://user-images.githubusercontent.com/47824996/226065016-497b4a86-fbd6-4fb9-9b98-f0b0e4286448.png)
![view pnr design tablet responsive](https://user-images.githubusercontent.com/47824996/226065018-eab3e8ba-a381-406f-8cb8-a79186773fe4.png)
![Accordion component-1](https://user-images.githubusercontent.com/47824996/226065019-8deb7c3b-45f5-4e94-99b2-dafe15a19052.png)
![View PNR Mobile](https://user-images.githubusercontent.com/47824996/226065020-c5982e6c-a91e-4255-b43a-8cc0db7ed535.png)
![accordion component](https://user-images.githubusercontent.com/47824996/226065021-bf3d8c4c-d6da-4e13-b475-88530bfc0c3e.png)
