### ISSUE TITLE
Node-sass and Orion Dependency Migration

### ISSUE THREAD

**Issue by aesthetiques** [AlaskaAirlines/auro-accordion#70]
# User story

There are multiple components that currently make use of this component, and when attempting to update to the newest auro design sass dependencies, we're seeing dependency tree conflicts due to node-sass and orion dependencies. 

![image](https://user-images.githubusercontent.com/25255197/218594641-b50e61a5-8bf6-48f4-98ba-5bb9663fc233.png)

## Outline subtasks or tasks

> List specific steps required to deliver this work.

- Migrate from orion to latest auro dependencies
- Migrate off of node-sass (I believe we're using dart-sass now?) 

## Definition of “Done” (exit criteria)

- There are no deprecated dependencies in the tree

**Comment by blackfalcon** [comment]
What needs to happen

1. remove ODS dependencies 
2. Update to Dart-Sass (node 16+ support)
3. The whole test harness and Husky support needs to be updated as well

**Comment by blackfalcon** [comment]
This is the first pass of this work, larger size score.
