### ISSUE TITLE
auro-accordion: implement default design

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-accordion#85]
### Is your feature request related to a problem? Please describe.

The auro-accordion component currently does not have any styling for the default usage.

The recently finished Figma blueprint needs to be implemented.

### Describe the solution you'd like

Complete update of component styles and API flags to implement final design.

### Additional context

Once these default examples are created we need to look at updating the AuroDocSite to use the new version of accordion.

**Comment by jordanjones243** [comment]
Figma for design: https://www.figma.com/file/jFPo0zwVENQVeOauFyHVuF/Accordion?type=design&node-id=1701-19321&mode=design&t=KamiAGb2u7ld3JnE-0
